echo "run lab4 projects"
echo "run eureka server project"
gnome-terminal -x sh -c "cd lab-4-eureka-server;  mvn spring-boot:run"
echo "run subject project"
gnome-terminal -x sh -c "cd lab-4-subject;  mvn spring-boot:run"
echo "run verb project"
gnome-terminal -x sh -c "cd lab-4-verb;  mvn spring-boot:run"
echo "run adjective project"
gnome-terminal -x sh -c "cd lab-4-adjective;  mvn spring-boot:run"
echo "run sentence project"
gnome-terminal -x sh -c "cd lab-4-sentence;  mvn spring-boot:run"
echo "Open http://localhost:8010/ to get to eureka server"
echo "Open http://localhost:8020/sentence to see the completed sentence"
echo "completed"