eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#spring:
#  cloud:
#    config:
#      uri: http://localhost:8001
      
words: ran,knew,had,saw,bought
server:
  port: ${PORT:${SERVER_PORT:0}}
